openapi: 3.0.0
servers:
  - url: 'http://localhost:8080'
  - url: 'https://localhost:8080'
  - url: 'http://articelph.herokuapp.com'
  
info:
  version: "0.0.1-oas3"
  title: Articelph
tags:
  - name: Application Configuration
  - name: Users
  - name: Articles
  - name: Categories
  - name: Languages
  - name: Links
  
  
paths:
      
  /api/secure/start-application:
    get:
      description: Is user authorized or unauthorized
      tags: 
       - Application Configuration
      security:
        - AuthorizationKey: []
          Udid: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
        '401':
          description: Unauthorization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
        '452':
          description: Unvalidation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'        
        
                
  /api/secure/links:
   get:
      description: Return permitted links
      tags:
        - Links
      security:
        - AuthorizationKey: []
          Udid: []
      responses:
        '200':
          description: Success
          content:
            application/json:
             schema:
              type: array
              items:
                $ref: '#/components/schemas/Link'


  /api/users:
    post:
     description: Create new user
     tags:
        - Users   
     security:
        - AuthorizationKey: []
          Udid: []   
     responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authorization'
     requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: false
  
  /api/secure/users/{userId}/profile:
    get:
     description: Get user's profile
     security:
        - AuthorizationKey: []
          Udid: []
     tags:
        - Users
     parameters: 
      - name: userId
        in: path
        required: true
        schema:
         type: string
     responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
    
    put:
     description: Get user's profile
     security:
        - AuthorizationKey: []
          Udid: []
     tags:
        - Users
     parameters: 
      - name: userId
        in: path
        required: true
        schema:
         type: string
      - name: area
        in: query
        required: true
        schema:
         type: string
         enum: ['PROFILEIMAGE','NAME','EMAILADRESS']
     responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
     requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                upload:
                  type: string
                  format: binary
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true            

  /api/secure/articles:
    get:
      description: Return articles list
      tags:
        - Articles
      security:
        - AuthorizationKey: []
          Udid: []  
      parameters:
        - name: category
          in: query
          schema:
            type: string
        - name: defaultLanguage
          in: query
          schema:
            type: string
        - name: transgerLanguage
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
    
    
    post:
      description: Create a new article
      tags:
        - Articles
      security:
        - AuthorizationKey: []
          Udid: []
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
        required: true
        
        
  /api/secure/categories:
    get:
      tags:
        - Categories
      security:
        - AuthorizationKey: []
          Udid: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
                  
  /api/secure/categories/{categoryId}/articles:
    get:
     tags: 
      - Categories
     security: 
      - AuthorizationKey: []
        Udid: []
     parameters: 
      - name: categoryId
        in: path
        required: true
        schema:
         type: string
     responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
                  
  /api/secure/languages:
    get:
      description: Return language list
      tags:
        - Languages
      security:
        - AuthorizationKey: []
          Udid: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Language'
  
  /api/secure/languages/{languageId}/articles:
   get:
      description: Return language's articles
      tags:
        - Languages
      security:
        - AuthorizationKey: []
          Udid: []
      parameters: 
       - name: languageId
         required: true
         in: path
         schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Language'
  
    
        
  /api/secure/articles/{articleId}:
   put:
    description: Take article
    tags:
        - Articles
    security:
        - AuthorizationKey: []
          Udid: []
    parameters: 
     - name: articleId
       in: path
       required: true
       schema:
          type: string
    responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
  
  
   get:
    description: Get an article
    tags:
        - Articles
    security:
        - AuthorizationKey: []
          Udid: []
    parameters: 
     - name: articleId
       in: path
       required: true
       schema:
          type: string      
    responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'  
        
        
        
  /swagger:
    x-swagger-pipe: swagger_raw
components:

  securitySchemes:
    AuthorizationKey:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: AuthorizationKey
    Udid:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: Udid  
  schemas:
    CommonResponse:
      properties:
        code:
          type: number
        message:
          type: string
      type: object
    User:
      properties:
        _id:
          type: string
        emailAdress:
          type: string
        name:
          type: string
        password:
          type: string
      type: object
    Authorization:
      properties:
        code:
          type: number
        message:
          type: string
        secretKey:
          type: string
      type: object
    Article:
      properties:
        _id:
          type: string
        category:
          type: string
        link:
          type: string
        status:
          type: string
        defaultLanguage:
          type: string
        transferLanguage:
          type: string
        thumbNailPhoto:
         type: string
        description:
         type: string
        postedBy:
          $ref: '#/components/schemas/User'
        translator:
          $ref: '#/components/schemas/User'
      type: object
    Category:
      properties:
        _id:
          type: string
        name:
          type: string
      type: object
    Language:
      properties:
        _id:
          type: string
        code:
          type: string
        name:
           type: string
        nativeName:
           type: string     
      type: object
    Profile:
     properties:
      profileImage:
       type: string
      user:
       $ref: '#/components/schemas/User'
      beforeTransferedArticleList:
       $ref: '#/components/schemas/Article'
      requestArticleList:
       $ref: '#/components/schemas/Article'
    Link:
     properties:
      _id:
       type: string
      link:
       type: string